### PR TITLE
 Adding custom methods to result

### PR DESCRIPTION
**Pull request by pierreluctg**

### CODE REVIEW

**Comment by pierreluctg** [comment]
FYI @travispavek

**Comment by pierreluctg** [comment]
Hi @travispavek let me know if you need more details on my changes.

Thank you

**Comment by travispavek** [comment]
@pierreluctg thanks for the pr.  I meant to look at it this weekend but some stuff came up.  I will look at it tonight or tomorrow.

**Comment by pierreluctg** [comment]
Hi @travispavek any update on this PR?

Thank you

**Comment by pierreluctg** [comment]
@travispavek looks like the Python 2.6 tests are failing.

Do you want to keep Python 2.6? https://www.python.org/dev/peps/pep-0361/#release-lifespan

**Comment by pierreluctg** [comment]
Thank you @travispavek

**Pull request merged**
